version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: giftspy_bot
    restart: always
    env_file:
      - .env
    volumes:
      # Важно: файлы сессий должны существовать до запуска docker-compose.
      - ./bot_session.session:/app/bot_session.session
      - ./user_session.session:/app/user_session.session
